# Default configuration for Jenkins Unity CI/CD
project_prefix: "unity-cicd"
aws_region: "us-east-1"
unity_version: "2023.2.20f1"

# Security Configuration
# 限制允许访问Jenkins的IP地址范围
allowed_cidrs:
  - "54.0.0.0/8"  # 当前IP
  - "15.0.0.0/8"  # 当前IP
  - "10.0.0.0/8"      # 内网IP
  - "172.16.0.0/12"   # 内网IP
  - "192.168.0.0/16"  # 内网IP
  # 添加您的公网IP范围，例如：
  # - "203.0.113.0/24"  # 您的公司IP范围
  # - "198.51.100.0/24" # 您的家庭IP范围

# Network Configuration
vpc:
  cidr: "10.0.0.0/16"
  availability_zones: 3
  
# Jenkins Master Configuration
jenkins_master:
  instance_type: "c5.large"
  volume_size: 20
  
# Jenkins Agent Configuration
jenkins_agents:
  instance_types:
    - "c5.2xlarge"
    - "c5.4xlarge"
    - "m5.2xlarge"
    - "m5.4xlarge"
    - "r5.2xlarge"
  max_instances: 10
  min_instances: 0
  desired_capacity: 2

# EBS Cache Pool Configuration
cache_pool:
  volume_size: 100
  volume_type: "gp3"
  iops: 3000
  throughput: 125
  min_volumes_per_az: 2
  max_age_days: 7

# EFS Configuration
efs:
  performance_mode: "generalPurpose"
  throughput_mode: "provisioned"
  provisioned_throughput: 100

# Monitoring Configuration
monitoring:
  enable_detailed_monitoring: true
  log_retention_days: 30
  enable_xray: false